#! /usr/bin/env python

from subprocess import check_output
from collections import defaultdict
from optparse import OptionParser






def opts():
    parser = OptionParser("usage: %prog [options] [args]")
    parser.add_option("-o", "--output", action="store", dest="one_screen"  ,
                      default=None, metavar="SCREEN",
                      help="Set output to one display")
    options,args = parser.parse_args()
    return options, args




def main():
    spawn_screen()
    #options, args = opts()
    #screens = get_screens()
    #print(screens)


if __name__=='__main__':
    main()
